name: nekoton_webview_example
description: Nekoton webview example
version: 1.12.0
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  bloc: ^9.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_inappwebview: 6.1.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  nekoton_webview:
    path: ../

dev_dependencies:
  bloc_test: ^10.0.0
  broxus_flutter_analysis:
    git:
      url: https://github.com/broxus/flutter_templates.git
      ref: broxus_flutter_analysis-v1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
