name: nekoton_webview_example
description: Nekoton webview example
version: 1.8.0-dev.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_inappwebview: 6.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  nekoton_webview:
    path: ../

dev_dependencies:
  bloc_test: ^9.1.1
  broxus_flutter_analysis:
    git:
      url: https://github.com/broxus/flutter_templates.git
      ref: broxus_flutter_analysis-v1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
