name: nekoton_webview
description: Flutter webview nekoton inpage provider bindings
version: 0.1.5
repository: https://github.com/broxus/nekoton_webview

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ">=5.0.0 <6.0.0"
  json_annotation: ^4.8.1
  logging: ^1.1.1

dev_dependencies:
  broxus_flutter_analysis:
    git:
      url: https://github.com/broxus/flutter_templates.git
      ref: broxus_flutter_analysis-v1.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  melos: ^3.0.1
  mocktail: ^1.0.0

flutter:
  assets:
    - assets/main.js
