name: nekoton_webview
description: Flutter webview nekoton inpage provider bindings
version: 0.2.1
repository: https://github.com/broxus/nekoton_webview

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  json_annotation: ^4.9.0
  logging: ^1.3.0

dev_dependencies:
  broxus_flutter_analysis:
    git:
      url: https://github.com/broxus/flutter_templates.git
      ref: broxus_flutter_analysis-v1.0.0
  build_runner: ^2.4.13
  commitlint_cli: ^0.8.1
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  json_serializable: ^6.9.0
  melos: ^7.3.0
  mocktail: ^1.0.4

flutter:
  assets:
    - assets/main.js

melos:
  useRootAsPackage: true
  scripts:
    build_and_test:
      description: GA main script
      run: bash scripts/build_and_test.sh

    analyze:
      exec: flutter analyze .
      description: Analyze a specific package in this project

    check-format:
      exec: dart format --set-exit-if-changed .
      failFast: true
      description: Check the format of a specific package in this project.

    test:
      run: melos run test:flutter --no-select
      description: Run all Dart & Flutter tests in this project.

    test:flutter:
      exec: "flutter test test"
      description: Run Flutter tests for a specific package in this project.
      concurrency: 1
      failFast: true
      packageFilters:
        flutter: true
        dirExists: test

    test:integration:
      exec: "flutter test --flavor development integration_test"
      description: Run Flutter teintegration teststs for a specific package in this project.
      concurrency: 1
      failFast: true
      packageFilters:
        flutter: true
        dirExists: integration_test

    generate-js:
      run: bash scripts/generate-js.sh
      description: Generate JS bindings

    codegen:
      run: bash scripts/codegen.sh
      description: Generate Dart inpage provider api bindings

    git-check:
      run: bash scripts/git-check.sh
      description: Check if some code changed during build

  command:
    clean:
      hooks:
        post: bash scripts/clean.sh

    version:
      hooks:
        preCommit: melos bs && git add --all
