name: nekoton_webview
description: Flutter webview nekoton inpage provider bindings
version: 0.1.8-dev.4
repository: https://github.com/broxus/nekoton_webview

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  json_annotation: ^4.9.0
  logging: ^1.3.0

dev_dependencies:
  broxus_flutter_analysis:
    git:
      url: https://github.com/broxus/flutter_templates.git
      ref: broxus_flutter_analysis-v1.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  melos: ^3.4.0
  mocktail: ^1.0.4

flutter:
  assets:
    - assets/main.js
