name: nekoton_webview
description: Flutter webview nekoton inpage provider bindings
version: 0.1.1-dev.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ">=5.0.0 <6.0.0"
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  melos: ^3.0.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  assets:
    - assets/main.js
