name: Build and test package

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build_and_test:
    uses: broxus/flutter_templates/.github/workflows/run-melos.yaml@v3
    with:
      flutter_version: '3.24.5'

  # ios-integration-test:
  #   uses: broxus/flutter_templates/.github/workflows/ios-integration-test.yaml@v2
  #   with:
  #     working-directory: ./example
  #     flutter_version: '3.24.5'

  android_integration_test:
    uses: broxus/flutter_templates/.github/workflows/android-integration-test.yaml@v3
    with:
      working-directory: ./example
      flutter_version: '3.24.5'
